import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NavMenu from './NavMenu'
import AuthProvider from './AuthProvider'
import Footer from './Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Myspace | Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <AuthProvider>
    <html lang="en">
      <body className="mx-auto h-screen justify-between">
        <NavMenu />
        <div className="pt-10">
        <div className="container flex mx-auto">
    <div className="lg:pr-4">
      <div className="lg:max-w-xlg h-screen">
         {children}
         </div></div>
         </div></div>
         <Footer />
        </body>
    </html>
    </AuthProvider>
  )
}
